# Generated by Django 5.0.4 on 2025-04-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAstore', '0004_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
