# Generated by Django 5.0.4 on 2025-04-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAstore', '0007_rename_customer_name_order_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email_address',
            field=models.EmailField(default=504215, max_length=254),
            preserve_default=False,
        ),
    ]
