# Generated by Django 5.0.4 on 2025-04-26 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAstore', '0010_product_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='postal_code',
        ),
    ]
