# Generated by Django 5.0.4 on 2025-04-26 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAstore', '0011_rename_phone_number_order_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='email_address',
            new_name='email',
        ),
    ]
