# Generated by Django 5.0.4 on 2025-04-26 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAstore', '0012_rename_email_address_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=90, max_digits=10),
            preserve_default=False,
        ),
    ]
